FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY kafka_consumers/ ./kafka_consumers/

CMD ["python", "kafka_consumers/kafka_to_redis_postgres.py"]
